add burgermenu, functionality and styling
CorneliusMoe/S.M.A.R.T.-App pull request #24
Opened 2023-07-22 15:46 UTC by CorneliusMoe

thanks for reviewing :)

2023-07-23 20:04 UTC, josch87 requested changes
Great work with the useEffect, state and handleClickOutside!

2023-07-23 20:04 UTC, josch87 commented on components/BurgerMenu/index.js
> +  }
Instead of selecting all button elements that are (direct?) children of the MenuItem component it would be more clean to create a styled-component for them as well (or rather a styled-component for the Next.js Link-Component).

2023-07-24 07:12 UTC, CorneliusMoe commented on components/BurgerMenu/index.js
> +  };
Changed it to normal functions :)

2023-07-24 07:14 UTC, CorneliusMoe commented on components/BurgerMenu/index.js
> +  top: 100%;
deleted the `top: 100% `

2023-07-24 07:16 UTC, CorneliusMoe commented on components/BurgerMenu/index.js
> +        <MenuList isOpen={isMenuOpen} ref={menuRef}>
thanks, did not know that, changed it

2023-07-24 07:18 UTC, CorneliusMoe commented on components/Header/Header.style.js
Thanks 👍

2023-07-24 07:35 UTC, CorneliusMoe commented on components/BurgerMenu/index.js
> +            </button>
Changed :)

2023-07-24 07:42 UTC, CorneliusMoe commented on components/BurgerMenu/index.js
> +  }
changed

2023-07-24 07:45 UTC, CorneliusMoe commented on pages/index.js
>            <HomeButton>Be S.M.A.R.T. today</HomeButton>
changed it

2023-07-24 08:17 UTC, CorneliusMoe commented on components/Header/Header.style.js
Thanks, I struggled with that warning for quite some time, this helped resolve that issue :)

2023-07-24 09:41 UTC, Frank-Schaeske commented
LGTM

2023-07-24 10:46 UTC, merged